"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.PROFILE_BLOB_PROPERTIES = exports.PROFILE_MANDATORY_PROPERTIES = exports.PROFILE_TYPES = exports.PEEK_DROP_DELAY = exports.PEEK_REPLICATION_WAIT_TIME = exports.ORBITDB_STORE_TYPE = exports.ORBITDB_STORE_NAME = void 0;
// Orbit DB
const ORBITDB_STORE_NAME = 'profile';
exports.ORBITDB_STORE_NAME = ORBITDB_STORE_NAME;
const ORBITDB_STORE_TYPE = 'keyvalue';
exports.ORBITDB_STORE_TYPE = ORBITDB_STORE_TYPE;
const PEEK_REPLICATION_WAIT_TIME = 60000;
exports.PEEK_REPLICATION_WAIT_TIME = PEEK_REPLICATION_WAIT_TIME;
const PEEK_DROP_DELAY = 60000 * 3; // Profile Properties

exports.PEEK_DROP_DELAY = PEEK_DROP_DELAY;
const PROFILE_TYPES = ['Person', 'Organization', 'Thing'];
exports.PROFILE_TYPES = PROFILE_TYPES;
const PROFILE_MANDATORY_PROPERTIES = ['@context', '@type', 'name'];
exports.PROFILE_MANDATORY_PROPERTIES = PROFILE_MANDATORY_PROPERTIES;
const PROFILE_BLOB_PROPERTIES = ['image'];
exports.PROFILE_BLOB_PROPERTIES = PROFILE_BLOB_PROPERTIES;